### ISSUE TITLE
Question: location of image, css, js ... files

### ISSUE THREAD

**Issue by svanimpe** [IBM-Swift/Kitura-TemplateEngine#13]
Where do I put images, stylesheets and scripts I need to reference in my templates? Is this even supported or do I need to set up a static file server to do this?

**Comment by shmuelk** [comment]
I don't think this is supported by the Kitura-TemplateEngine framework. I would use the StaticFileServer middleware to do this.

**Comment by svanimpe** [comment]
OK thanks, then I will do the same.

**Comment by Andrew-Lees11** [comment]
Closing since question appears to have been answered.

**Comment by svanimpe** [comment]
@Andrew-Lees11 Yes, the StaticFileServer middleware works fine for this.
